data_path: "data/"
vector_store_path: "vector_db/"
edgar_user_agent: "Name Surname email"

chunk_size: 1500
chunk_overlap: 200

embedding_model_name: "all-MiniLM-L6-v2"

llm_model_name: "gpt-3.5-turbo-0125"